id = "rover"
name = "Rover"
version = "0.1.0"
schema_version = 1
authors = ["Isaac Harris-Holt <isaac@getrover.com>"]
description = "The Zed extension for Rover, the code reliability platform for fast-moving teams."
repository = "https://github.com/rover-app/zed-extension"

[context_servers.rover]
